"""initial_schema

Revision ID: c2d788795e20
Revises: 
Create Date: 2026-07-08 18:50:49.145230
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2d788795e20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=True)
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('estados_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('color_badge', sa.String(length=7), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.Column('es_cancelacion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('orden')
    )
    op.create_table('galeria_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 1 AND 7', name='ck_horarios_dia'),
    sa.CheckConstraint('hora_inicio < hora_fin', name='ck_horarios_horas'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia_semana')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('pais_origen', sa.String(length=50), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('niveles_suciedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('segmentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tipos_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('rol', sa.String(length=15), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rol IN ('admin', 'empleado')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_table('box_tipo_vehiculo',
    sa.Column('tipo_box_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_box_id'], ['tipos_box.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('tipo_box_id', 'tipo_vehiculo_id')
    )
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_box_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tipo_box_id'], ['tipos_box.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_boxes_activo'), 'boxes', ['activo'], unique=False)
    op.create_index(op.f('ix_boxes_tipo_box_id'), 'boxes', ['tipo_box_id'], unique=False)
    op.create_table('galeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.Column('url_thumb', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['galeria_categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('anio_desde', sa.SmallInteger(), nullable=True),
    sa.Column('anio_hasta', sa.SmallInteger(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('anio_desde IS NULL OR anio_hasta IS NULL OR anio_desde <= anio_hasta', name='ck_modelos_anios'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marca_id', 'slug', name='uq_modelos_marca_slug')
    )
    op.create_index(op.f('ix_modelos_vehiculo_marca_id'), 'modelos_vehiculo', ['marca_id'], unique=False)
    op.create_index(op.f('ix_modelos_vehiculo_tipo_vehiculo_id'), 'modelos_vehiculo', ['tipo_vehiculo_id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_servicio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('requiere_inspeccion_previa', sa.Boolean(), nullable=False),
    sa.Column('requiere_varios_dias', sa.Boolean(), nullable=False),
    sa.Column('dias_bloqueo', sa.SmallInteger(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo IN ('base', 'adicional', 'paquete')", name='ck_servicios_tipo'),
    sa.CheckConstraint('requiere_varios_dias = FALSE OR dias_bloqueo IS NOT NULL', name='ck_servicios_dias'),
    sa.ForeignKeyConstraint(['categoria_servicio_id'], ['categorias_servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_servicios_categoria_servicio_id'), 'servicios', ['categoria_servicio_id'], unique=False)
    op.create_table('testimonios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('valoracion', sa.SmallInteger(), nullable=False),
    sa.Column('vehiculo_descripcion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valoracion BETWEEN 1 AND 5', name='ck_testimonios_valoracion'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquete_servicios',
    sa.Column('paquete_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('paquete_id <> servicio_id', name='ck_paquete_principal'),
    sa.ForeignKeyConstraint(['paquete_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('paquete_id', 'servicio_id')
    )
    op.create_index(op.f('ix_paquete_servicios_paquete_id'), 'paquete_servicios', ['paquete_id'], unique=False)
    op.create_table('precios_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('nivel_suciedad_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('duracion_minutos', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duracion_minutos > 0', name='ck_duracion_positiva'),
    sa.CheckConstraint('precio >= 0', name='ck_precio_positivo'),
    sa.ForeignKeyConstraint(['nivel_suciedad_id'], ['niveles_suciedad.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'tipo_vehiculo_id', 'segmento_id', 'nivel_suciedad_id', name='uq_precio_combinacion')
    )
    op.create_index(op.f('ix_precios_servicio_servicio_id'), 'precios_servicio', ['servicio_id'], unique=False)
    op.create_table('servicio_tipo_vehiculo',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('servicio_id', 'tipo_vehiculo_id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('marca_texto', sa.String(length=50), nullable=True),
    sa.Column('modelo_texto', sa.String(length=80), nullable=True),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('chapa', sa.String(length=15), nullable=True),
    sa.Column('combustible', sa.String(length=20), nullable=True),
    sa.Column('transmision', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(marca_id IS NOT NULL AND modelo_id IS NOT NULL) OR (marca_texto IS NOT NULL AND modelo_texto IS NOT NULL)', name='ck_vehiculos_catalogado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_cliente_id'), 'vehiculos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vehiculos_modelo_id'), 'vehiculos', ['modelo_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('estado_reserva_id', sa.Integer(), nullable=False),
    sa.Column('nivel_suciedad_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('duracion_total_min', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('hora_entrega_estimada', sa.Time(), nullable=True),
    sa.Column('precio_estimado_base', sa.Integer(), nullable=False),
    sa.Column('precio_estimado_adicionales', sa.Integer(), nullable=False),
    sa.Column('precio_final_base', sa.Integer(), nullable=True),
    sa.Column('precio_final_adicionales', sa.Integer(), nullable=True),
    sa.Column('motivo_ajuste_precio', sa.Text(), nullable=True),
    sa.Column('confirmacion_token', sa.String(length=64), nullable=True),
    sa.Column('observaciones_cliente', sa.Text(), nullable=True),
    sa.Column('observaciones_internas', sa.Text(), nullable=True),
    sa.Column('reagendado_de', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duracion_total_min > 0', name='ck_duracion_positiva'),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_reserva_id'], ['estados_reserva.id'], ),
    sa.ForeignKeyConstraint(['nivel_suciedad_id'], ['niveles_suciedad.id'], ),
    sa.ForeignKeyConstraint(['reagendado_de'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmacion_token')
    )
    op.create_index('ix_reservas_box_fecha_hora', 'reservas', ['box_id', 'fecha', 'hora_inicio'], unique=False)
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_reservas_created_at'), 'reservas', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservas_estado_reserva_id'), 'reservas', ['estado_reserva_id'], unique=False)
    op.create_index(op.f('ix_reservas_fecha'), 'reservas', ['fecha'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_asignado_id'), 'reservas', ['usuario_asignado_id'], unique=False)
    op.create_table('solicitudes_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_texto', sa.String(length=50), nullable=False),
    sa.Column('modelo_texto', sa.String(length=80), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_aprobador_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'aprobada', 'rechazada')", name='ck_solicitudes_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['usuario_aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_catalogo_estado'), 'solicitudes_catalogo', ['estado'], unique=False)
    op.create_table('estados_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior_id', sa.Integer(), nullable=False),
    sa.Column('estado_nuevo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_email', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estado_anterior_id'], ['estados_reserva.id'], ),
    sa.ForeignKeyConstraint(['estado_nuevo_id'], ['estados_reserva.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_cambio_created_at'), 'estados_cambio', ['created_at'], unique=False)
    op.create_index(op.f('ix_estados_cambio_reserva_id'), 'estados_cambio', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_estados_cambio_usuario_id'), 'estados_cambio', ['usuario_id'], unique=False)
    op.create_table('fotografias_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.Column('url_thumb', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('antes', 'despues')", name='ck_fotografias_tipo'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotografias_reserva_reserva_id'), 'fotografias_reserva', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_fotografias_reserva_tipo'), 'fotografias_reserva', ['tipo'], unique=False)
    op.create_table('reserva_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('precio_aplicado', sa.Integer(), nullable=False),
    sa.Column('tiempo_aplicado_min', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('precio_aplicado >= 0', name='ck_precio_adicional'),
    sa.CheckConstraint('tiempo_aplicado_min > 0', name='ck_tiempo_adicional'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', 'servicio_id', name='uq_reserva_adicional')
    )
    op.create_index(op.f('ix_reserva_adicionales_reserva_id'), 'reserva_adicionales', ['reserva_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_adicionales_reserva_id'), table_name='reserva_adicionales')
    op.drop_table('reserva_adicionales')
    op.drop_index(op.f('ix_fotografias_reserva_tipo'), table_name='fotografias_reserva')
    op.drop_index(op.f('ix_fotografias_reserva_reserva_id'), table_name='fotografias_reserva')
    op.drop_table('fotografias_reserva')
    op.drop_index(op.f('ix_estados_cambio_usuario_id'), table_name='estados_cambio')
    op.drop_index(op.f('ix_estados_cambio_reserva_id'), table_name='estados_cambio')
    op.drop_index(op.f('ix_estados_cambio_created_at'), table_name='estados_cambio')
    op.drop_table('estados_cambio')
    op.drop_index(op.f('ix_solicitudes_catalogo_estado'), table_name='solicitudes_catalogo')
    op.drop_table('solicitudes_catalogo')
    op.drop_index(op.f('ix_reservas_usuario_asignado_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_estado_reserva_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_created_at'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.drop_index('ix_reservas_box_fecha_hora', table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_vehiculos_modelo_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_cliente_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('servicio_tipo_vehiculo')
    op.drop_index(op.f('ix_precios_servicio_servicio_id'), table_name='precios_servicio')
    op.drop_table('precios_servicio')
    op.drop_index(op.f('ix_paquete_servicios_paquete_id'), table_name='paquete_servicios')
    op.drop_table('paquete_servicios')
    op.drop_table('testimonios')
    op.drop_index(op.f('ix_servicios_categoria_servicio_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_modelos_vehiculo_tipo_vehiculo_id'), table_name='modelos_vehiculo')
    op.drop_index(op.f('ix_modelos_vehiculo_marca_id'), table_name='modelos_vehiculo')
    op.drop_table('modelos_vehiculo')
    op.drop_table('galeria')
    op.drop_index(op.f('ix_boxes_tipo_box_id'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_activo'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_table('box_tipo_vehiculo')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_vehiculo')
    op.drop_table('tipos_box')
    op.drop_table('segmentos')
    op.drop_table('niveles_suciedad')
    op.drop_table('marcas')
    op.drop_table('horarios')
    op.drop_table('galeria_categorias')
    op.drop_table('estados_reserva')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('categorias_servicio')
    # ### end Alembic commands ###
